# Generated by Django 2.0.7 on 2019-03-10 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carfinderapp', '0002_auto_20190210_1441'),
    ]

    operations = [
        migrations.RenameField(
            model_name='model',
            old_name='manufacturer_name',
            new_name='manufacturer',
        ),
    ]
