# Generated by Django 2.0.7 on 2019-03-10 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carfinderapp', '0003_auto_20190310_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snoopdetail',
            old_name='manufacturer_name',
            new_name='manufacturer',
        ),
        migrations.RenameField(
            model_name='snoopdetail',
            old_name='model_name',
            new_name='model',
        ),
    ]
